# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0002_auto_20160708_0948'),
        ('myAuth', '0002_auto_20160708_0949'),
    ]

    operations = [
    ]
